name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install buck
        run: |
          wget https://github.com/facebook/buck/releases/download/v2019.10.17.01/buck.2019.10.17.01_all.deb
          dpkg -i buck.2019.10.17.01_all.deb

      - name: Build
        run: buck build :ext2fs
