name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Buck build
        uses: GuilleDF/buckaroo-action@v1.0.3
        with:
          commands: |
            curl -L https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb -o /tmp/dkp-pkm.deb;
            dpkg -i /tmp/dkp-pkm.deb;
            dkp-pacman -S --noconfirm wii-dev;
            buck build :ext2fs;
