name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install buck
      run: |
        mkdir -p bin
        wget https://github.com/njlr/buck-warp/releases/download/v0.3.0/buck-2019.01.10.01-linux -O bin/buck
        chmod +x bin/buck

    - name: Build
      run: ./bin/buck build :ext2fs
